name: ${name}
description: ${description}
version: ${version}
author: Khron. Para más información ver repositorio de GitHub
main: org.aylas.khron.tiemporeal.PluginTiempoReal
depend: [LibConfig]
api-version: '1.21.8'
commands:
    trconfig:
        description: Cambia la configuración.
        aliases: trcfg
        permission: tiemporeal.trconfig
        permission-message: ""
        usage: "Sintaxis: /<command> [parámetro] [valor]"
    trrecargarconfig:
        description: Recarga la configuración.
        aliases: [ trrecargarcfg, trreccfg, trrecconfig ]
        permission: tiemporeal.trrecargarconfig
        permission-message: ""
        usage: "Sintaxis: /<command>"
permissions:
    tiemporeal.*:
        description: Permite acceso total a los comandos del plugin.
        default: op
        children:
            tiemporeal.trconfig.*: true
            tiemporeal.trrecargarconfig: true
    tiemporeal.trconfig.*:
        description: Permite cambiar todos los parámetros de configuración del plugin.
        children:
            tiemporeal.trconfig.mundosSimulacionYParametros: true
            tiemporeal.trconfig.textoReloj: true
            tiemporeal.trconfig.textoRelojDimensionSinCiclo: true
            tiemporeal.trconfig.claveWeatherbit: true
    tiemporeal.trconfig.mundosSimulacionYParametros:
        description: Permite cambiar los mundos en los que ${name} simula un ciclo diurno de longitud realista, junto con los parámetros usados para la simulación del ciclo diurno.
    tiemporeal.trconfig.textoReloj:
        description: Permite cambiar el texto que ${name} mostrará a los jugadores cuando empuñen un reloj.
    tiemporeal.trconfig.textoRelojDimensionSinCiclo:
        description: Permite cambiar el texto que ${name} mostrará a los jugadores cuando empuñen un reloj, en dimensiones donde no hay un ciclo día-noche.
    tiemporeal.trconfig.claveWeatherbit:
        description: Establece la clave a usar para autenticarse contra la API de Weatherbit.
    tiemporeal.trrecargarconfig:
        description: Permite recargar la configuración de ${name} desde disco.