name: Maven CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Configuración JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: graalvm

      - name: Compilar con Maven
        run: mvn -B package

      - name: Subir JARs generados
        uses: actions/upload-artifact@v7
        with:
          name: JARs plugins
          path: jar
